import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { buildSnapshot } from '../lib/snapshot.mjs'
const root=mkdtempSync(join(tmpdir(),'process-snapshot-'))
const map={title:'Demo',stages:['Start','Follow up'],nodes:[{id:'page',stage:'Start',kind:'page',title:'Page',purpose:'Start',source:'demo/page/'},{id:'series',stage:'Follow up',kind:'series',title:'Series',purpose:'Follow up',source:'.mailings/storage/processes/demo/series/'}],links:[{from:'page',to:'series',when:'After one day',via:'demo/automations/'}],needsInput:[{title:'Approve texts',nodeId:'series'}]}
mkdirSync(join(root,'demo/page'),{recursive:true});mkdirSync(join(root,'demo/automations'),{recursive:true});mkdirSync(join(root,'.mailings/storage/processes/demo/series'),{recursive:true})
writeFileSync(join(root,'.mailings/storage/processes/demo/series/01.message.yaml'),'title: Hello\nsubject: Your booking\n')
writeFileSync(join(root,'demo/automations/test.automationConfig.json'),JSON.stringify({steps:[{type:'delay',delay:{type:'delay',amount:1,units:'days'}},{type:'condition',conditionName:'Paid?',thenBranch:{steps:[{type:'action',actionName:'Thank you',params:{letterPath:'.mailings/storage/processes/demo/series/01.message.yaml'}}]},elseBranch:{steps:[{type:'action',actionName:'Reminder',params:{letterPath:'.mailings/storage/processes/demo/series/01.message.yaml'}}]}}]}))
const build=(extra={})=>buildSnapshot({root,slug:'demo',map,checks:[],branch:'process/demo',commit:'a'.repeat(40),...extra})
test('letters, action branches and needs-input survive in snapshot',()=>{const s=build();assert.equal(s.nodes[1].status,'needs-input');assert.equal(s.nodes[1].letters[0].subject,'Your booking');assert.equal(s.links[0].steps.length,4);assert.match(s.links[0].steps[2].title,/Thank you/);assert.match(s.links[0].steps[3].title,/Reminder/);assert.doesNotMatch(s.links[0].steps[0].detail,/[{}]/)})
test('automation file paths survive in snapshot',()=>{assert.deepEqual(build().links[0].automationFiles,['demo/automations/test.automationConfig.json'])})
test('agent path and explicit runtime ID survive in snapshot',()=>{const agent={id:'helper',stage:'Follow up',kind:'agent',title:'Helper',purpose:'',source:'demo/agents/helper.agent.json',agentId:'agent-42'};const nodes=build({map:{...map,nodes:[...map.nodes,agent]}}).nodes;assert.equal(nodes[2].kind,'external');assert.deepEqual(nodes[2].agent,{path:agent.source,id:'agent-42'});assert.deepEqual(build({map:{...map,nodes:[...map.nodes,{...agent,agentId:undefined}]}}).nodes[2].agent,{path:agent.source})})
test('snapshot bounds long diagnostics to the Start contract without hiding local check output',()=>{const errors=Array.from({length:102},(_,i)=>`Ошибка ${i}: `+'x'.repeat(2100));const snapshot=build({checks:[{id:'long',title:'Большая проверка',ok:false,errors,warnings:[]}]});assert.equal(snapshot.checks[0].errors.length,100);assert.ok(snapshot.checks[0].errors.every(item=>item.length<=2000));assert.equal(errors.length,102)})
test('agent runtime ID is accepted only on an agent source',()=>{assert.throws(()=>build({map:{...map,nodes:[{...map.nodes[0],agentId:'agent-42'}]}}),/Invalid agentId/);assert.throws(()=>build({map:{...map,nodes:[{...map.nodes[0],source:'demo/agents/helper.agent.json',agentId:'  '}]}}),/Invalid agentId/)})
test('multiple automation files keep separate paths',()=>{const second=join(root,'demo/automations/other.automationConfig.json');writeFileSync(second,JSON.stringify({steps:[]}));try{assert.deepEqual(build().links[0].automationFiles,['demo/automations/other.automationConfig.json','demo/automations/test.automationConfig.json'])}finally{rmSync(second)}})
test('absent source is missing even when it needs approval',()=>{const s=build({map:{...map,nodes:map.nodes.map(n=>({...n,source:'absent/'}))}});assert.equal(s.nodes[1].status,'missing')})
test('invalid maps are not published as empty or healthy',()=>assert.throws(()=>build({checks:[{id:'map',ok:false,errors:['invalid'],warnings:[]}]})))
test('traversal is rejected before reading files',()=>assert.throws(()=>build({map:{...map,nodes:[{...map.nodes[0],source:'../outside'}]}})))
test('path-specific errors override existence',()=>{const s=build({checks:[{id:'code',ok:false,errors:['demo/page/index.ts is broken'],warnings:[]}]});assert.equal(s.nodes[0].status,'error')})
test('stage-only failures do not change node state or reason',()=>{const stable=build();const launch=build({checks:[{id:'automation.smoke',ok:false,errors:['demo/page/: safe run pending'],warnings:[]},{id:'launch.variables',ok:false,errors:['price empty'],warnings:[]}]});assert.deepEqual(launch.nodes,stable.nodes)})
test('shared automation omits another series and its trailing waits',()=>{const other={...map,nodes:[...map.nodes,{id:'other',stage:'Follow up',kind:'series',title:'Other',purpose:'',source:'.mailings/storage/processes/demo/other/'}],links:[{from:'page',to:'other',via:'demo/automations/',when:'Now'}]};assert.equal(build({map:other}).links[0].steps.length,0)})
process.on('exit',()=>rmSync(root,{recursive:true,force:true}))
